export const ActionType = {
	GET_COUNTRY_BEGIN: "GET_COUNTRY_BEGIN",
	GET_COUNTRY_SUCCESS: "GET_COUNTRY_SUCCESS",
	GET_COUNTRY_FAILED: "GET_COUNTRY_FAILED",
	GET_CITY_BEGIN: "GET_CITY_BEGIN",
	GET_CITY_SUCCESS: "GET_CITY_SUCCESS",
	GET_CITY_FAILED: "GET_CITY_FAILED",
	GET_MEASUREMENT_BEGIN: "GET_MEASUREMENT_BEGIN",
	GET_MEASUREMENT_SUCCESS: "GET_MEASUREMENT_SUCCESS",
	GET_MEASUREMENT_FAILED: "GET_MEASUREMENT_FAILED",
};
